<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration
{
    public function up(): void
    {
        Schema::create(config()->string('activitylogger.table_name'), function (Blueprint $table) {
            $table->id();
            $table->integer('made_by_model_id');
            $table->string('made_by_model_type')->nullable();

            $table->json('human_message')->nullable();
            $table->json('human_extra_message')->nullable();

            // automatically generated by the application
            $table->json('application_message')->nullable();
            $table->json('application_extra_message')->nullable();
            // /for developer
            $table->json('developer_message')->nullable();
            $table->json('developer_extra_message')->nullable();
            $table->timestamps();
        });

    }

    public function down(): void
    {
        Schema::dropIfExists(config()->string('activitylogger.table_name'));

    }
};
